apiVersion: bindings.knative.dev/v1beta1
kind: KafkaBinding
metadata:
  name: <todo>
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service
  bootstrapServers:
    - <todo>