apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: <todo>
spec:
  broker: <todo>
  filter:
    attributes:
      type: dev.knative.kafka.event
      source: <todo>
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment-service
    uri: <todo>