apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: payment-trigger
spec:
  broker: pminkows-broker
  filter:
    attributes:
      type: dev.knative.kafka.event
      source: /apis/v1/namespaces/pminkows-serverless/kafkasources/kafka-source-to-broker#order-events
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment-service
    uri: /reserve