apiVersion: bindings.knative.dev/v1beta1
kind: KafkaBinding
metadata:
  name: kafka-binding-product-saga
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: product-saga
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092