apiVersion: eventing.knative.dev/v1alpha1
kind: KafkaSink
metadata:
  name: stock-sink
  namespace: demo-eventing
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topic: reserve-events
  numPartitions: 1