apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source-orders-product
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  consumerGroup: stock
  topics:
    - order-events
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: pminkows-broker